volumes:
  grafana-storage:
  postgres-data:
  mailpit-data:
  prometheus_data:

networks:
  ascent:
    driver: bridge

services:
  grafana:
    #image: grafana/grafana-oss:latest
    image: systemdevformations/grafana:12.3.2
    container_name: grafana
    ports:
      - "32400:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      #- GF_SECURITY_ADMIN_PASSWORD=p4ssw0rd
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug # Pour débugger si besoin
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=mailpit:1025
      - GF_SMTP_FROM_ADDRESS=alert@grafana.local
      - GF_SMTP_SKIP_VERIFY=true
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - ascent
  renderer:
    #image: grafana/grafana-image-renderer:latest
    image: systemdevformations/grafana-image-renderer:5
    container_name: renderer
    ports:
      - "8081"
    # Configuration pour éviter les problèmes de mémoire sur AlmaLinux
    environment:
      - ENABLE_METRICS=true
      - BROWSER_BIN=/usr/bin/google-chrome
      - IGNORE_HTTPS_ERRORS=true
    restart: unless-stopped
    depends_on:
      - grafana
    networks:
      - ascent

  mailpit:
    #image: axllent/mailpit:latest
    image: systemdevformations/mailpit:1.29.0
    container_name: mailpit
    environment:
      MP_DATABASE: /data/mailpit.db
      # MP_UI_AUTH_FILE: /data/authfile
    ports:
      - "30025:8025" # Interface Web pour voir les mails
      - "31025:1025" # Port SMTP pour Grafana
    volumes:
      - mailpit-data:/data
    restart: unless-stopped
    networks:
      - ascent

  prometheus:
    hostname: prometheus
    container_name: prometheus
    image: prom/prometheus:v3.5.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "32430:9090"
    restart: unless-stopped
    networks:
      - ascent

  postgres-db:
    image: postgres:15-alpine3.16
    container_name: postgres-db
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password_772
    ports:
      - "32420:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ascent
