volumes:
  grafana-storage:
  postgres-data:

networks:
  default:
    name: ascent
    driver: bridge

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "32400:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=p4ssw0rd
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug # Pour débugger si besoin
    restart: unless-stopped

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: grafana_renderer
    ports:
      - "8081"
    # Configuration pour éviter les problèmes de mémoire sur AlmaLinux
    environment:
      - ENABLE_METRICS=true
      - BROWSER_BIN=/usr/bin/google-chrome
      - IGNORE_HTTPS_ERRORS=true
    restart: unless-stopped

  postgres-db:
    image: postgres:15-alpine3.16
    container_name: postgres_db
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password_772
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

