volumes:
  grafana-storage:
  postgres-data:

networks:
  default:
    name: ascent
    driver: bridge

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "32400:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=p4ssw0rd
    restart: unless-stopped

  postgres-db:
    image: postgres:15-alpine3.16
    container_name: postgres_db
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password_772
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

