global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['192.168.1.70:32440']

scrape_configs:
  - job_name: grafana
    static_configs:
      - targets: ['192.168.1.70:32400']
  - job_name: prometheus
    static_configs:
      - targets: ['192.168.1.70:32430']
  - job_name: postgres-exporter
    static_configs:
      - targets: ['192.168.1.70:9187']
